version: '3.5'
services:
    com-6ix-auth0-user-prov:
        container_name: auth0-authn-nodejs-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "8088:8088"
        restart: always
        image: malotian/auth0-authn-nodejs-app:latest

networks:
    docker.local:
       driver: bridge
       name: docker.local
       